<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.6/semantic.min.css">
        <script src="https://cdn.jsdelivr.net/semantic-ui/2.2.6/semantic.min.js"></script>
    </head>
    <body>
        <div class="ui raised very padded text container segment ">
            <a href="<?= $uri ?>" class="ui basic button">
                <i class="icon arrow left"></i>
                Volver
            </a>
            <?php if (isset($userInfo)): ?>
                <h2 class="ui header">
                    <img src="http://semantic-ui.com/images/icons/plugin.png">
                    <div class="content">
                        Detalles del usuario
                    </div>
                </h2>
                <div class="ui link cards">
                    <div class="card">
                        <div class="image">
                            <img src="<?= ($userInfo['gender'] === 'male') ? 'http://semantic-ui.com/images/avatar2/large/matthew.png' : 'http://semantic-ui.com/images/avatar2/large/molly.png'; ?>">
                        </div>
                        <div class="content">
                            <div class="header"><?= $userInfo['name'] ?></div>
                            <div class="meta">
                                <a><?= $userInfo['position'] ?></a>
                            </div>
                            <div class="description">
                                <div class="ui list">
                                    <div class="item">
                                        <i class="volume control phone icon"></i>
                                        <div class="content">
                                            <?= $userInfo['phone'] ?>
                                        </div>
                                    </div>
                                    <div class="item">
                                        <i class="arrow right icon"></i>
                                        <div class="content">
                                            <?= $userInfo['address'] ?>
                                        </div>
                                    </div>
                                    <div class="item">
                                        <i class="mail icon"></i>
                                        <div class="content">
                                            <a href="mailto:<?= $userInfo['email'] ?>"><?= $userInfo['email'] ?></a>
                                        </div>
                                    </div>                                    
                                    <div class="item">
                                        <i class="money icon"></i>
                                        <div class="content">
                                            <?= $userInfo['salary'] ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="ui styled accordion">
                                    <div class="title">
                                        <i class="trophy icon"></i>
                                        Habilidades
                                    </div>
                                    <div class="content">
                                        <ul>
                                            <?php foreach ($userInfo['skills'] as $skill): ?>
                                                <li><?= $skill['skill'] ?></li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>                                                
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            <?php else : ?>
                <div class="ui negative message">
                    <div class="header">
                        Lo sentimos!
                    </div>
                    <p>No existe usuario con este id: <?= $id ?>
                    </p>
                </div>
            <?php endif; ?>

        </div>
    </body>
    <script>
        (function () {
            $('.ui.accordion').accordion();
        })();
    </script>
</html>
